### ISSUE TITLE
Feature Request: Support On-the-Fly Filtering for RSS Feeds

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#119]
I would like to request a feature to support on-the-fly requests to filter RSS feeds using basic functions like `keep_only`, `discard`, `readability`, `source`, and `limit`. This would allow users to apply simple filters directly through the interface/url without needing to create entries in `funnel.yaml`.

#### Proposed Features:
1. **keep_only**: Retain only the items that match the specified criteria.
2. **discard**: Remove items that match the specified criteria.
3. **readability**: Enhance the readability of feed items.
4. **source**: Filter items based on the source.
5. **limit**: Restrict the number of items displayed from the feed.

These filters can be used for quick and simple modifications. For advanced filtering, users can still define more complex rules in `funnel.yaml`.

#### Example:
To illustrate the proposed functionality, consider the following example URL:

http://127.0.0.1:4080/?source=http://example.com/feed&limit=5&discard=sponsor&readability

This URL would:
- Fetch the feed from `http://example.com/feed`.
- Limit the results to 5 items.
- Discard any items that contain the word "sponsor".
- Apply readability enhancements to the feed items.

#### Benefits:
- **Convenience**: Quick and easy filtering without modifying `funnel.yaml`.
- **Flexibility**: Users can apply and test filters on the fly, making it more user-friendly.
- **Efficiency**: Saves time for users who need to make small changes without going through the process of editing and reloading the configuration file.

Thank you for considering this feature request. I believe it will greatly enhance the usability of RSS Funnel for all users.

**Comment by shouya** [comment]
Sounds like a good idea. I would like to extend it as follows:

- First, we shall allow `keep_only`, `discard`, `readability`, `limit` parameters to be specified for any feed's endpoint. If supplied, the feed will be filtered accordingly in addition to existing filters. For the time being I'm considering gating these extra filter via an extra endpoint configuration (e.g. `on-the-fly-filters: true`).
- Then, since we already support dynamic sources, the `source` can be already be specified arbitrarily.

Then another thing we need to decide is the order of these filters to apply. We have two options:

- Use the specified order, e.g. `&limit=5&discard=sponsor` results in 
- Use a predefined

**Comment by shouya** [comment]
> Regarding the limit parameter, I think it should limit the source feeds first. Applying limit after discard or keep_only might result in fewer items than desired, as the filtering could reduce the number of results below the specified limit.

I'm suggesting limiting on the result for ergonomic purpose. I'm guessing the use case for this filter would be to limit the final output to contain at most N element. In terms of implementation, discard/keep_only filters runs cheaply (unlike readability, which is much more cpu-intensive), so there is no problem run them on all the entries upfront. I'd like to learn your specific use cases where limiting the source would make more sense?

> I'm not sure about the best practices, but I recommend following them even if it means having fewer features initially.

I fully agree. But the difficult thing is that having this set of on-the-fly filters that are different from the regular filters risk maintaining two sets of different yet similar kinds of filters that can create confusion and difficulty in maintenance. So my current idea is to allow existing filters to be used in an inline fashion. By which I mean the filters can be specified on-demand using query parameter.

> Examples include discard_title, discard_descriptions, discard_authors, and discard_categories, as well as similar filters for keep_only.

How about supporting both:

- `?source=xxx&discard.field=description&discard.contains=keyword` and
- `?source=xxx&discard=keyword`

As my point above, I'm trying to avoid introducing two kinds of filters if possible. This "syntax" will allow the existing filters to be used in a different way.

**Comment by shouya** [comment]
Let me first address some of your concerns.

> IP rate limiting or being banned for readability.

Readability is a little cpu-intensive but doesn't cause any external requests. Do you mean "full_text"? Also, since readability filter is one-to-one, we can apply limit before that and get the same result.

> CPU usage on low-powered devices.

This can be tackled by introducing post entry-level cache. There were works done for full-text: https://github.com/shouya/rss-funnel/pull/112, and I believe we can apply this kind of cache to entries in the whole pipeline in the future.

Nonetheless, now I lean towards making it that the order of the query params maps to the order of the filters applied, so it's more flexible how you would like the filters to compose.

------

> Some feeds don't have proper unique IDs, so every time the feed reader fetches the feed, it shows the same items as new. To avoid this, I usually limit the sources by the duration to prevent duplicate entries.

I saw this problem in the past. But I don't see how limiting the source would make a difference comparing to limiting the result. If you limit by `1h`, then you'll only get post published from the most recent hour, regardless it's limiting the source or the result.

> This looks complicated and goes against the goal of making it simple to create rules on the fly. It's better to stick with funnel.yaml for advanced configuration.

Then one thing we can do is to only allow scalar configs to existing filters. By "scalar" I mean the simple one-line number/string arguments without deep fields.
