### ISSUE TITLE
Feature Request: Support Multiple YAML Configuration Files

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#126]
Please add support for reading configuration from multiple YAML files. For example, the application could read all YAML files in a `config.d` directory and merge them into a single configuration.

**Comment by shouya** [comment]
I understand that you want something like splitting the config for endpoints in their own file. However, currently they're all placed under the same `endpoints` key, which makes merging them non-trivial because you can't just concatenate all the config files together. Otherwise attaching each `config.d` file's content into the `endpoints` key is not very intuitive to the users about its semantics. So I'm not planning to implement to support for config spanning multiple files.

That said, you can still try having config files defined in the way you want. I believe you can use tools like `yq` to preprocess the config files before supplying them to rss-funnel.
